from transformers import BertTokenizer, BertForTokenClassification
from transformers import pipeline

tokenizer = BertTokenizer.from_pretrained('tartuNLP/EstBERT_NER')
bertner = BertForTokenClassification.from_pretrained('tartuNLP/EstBERT_NER')

nlp = pipeline("ner", model=bertner, tokenizer=tokenizer)
sentence = '2017) selgub, et 77% Eesti üle 15- aastastest kasutajatest loeb alati läbi, milliste õigustega antud veebilehe või aplikatsiooni kasutamisel nõustuma peab, mis on iseenesest väga muljetavaldav number. Kuigi uuringust ei selgu kui suur osakaal vastanutest tegelikult ei saa nendest õigustest aru, siis tõmmatakse paralleel rahuvsvaheliselt läbiviidud uuringule. Iga sotsiaalmeedia platvormi kasutama asumisega nõustub kasutaja teatud õigustega, nii näiteks on õigus Facebook’il jagada, aga mitte müüa, kasutajate Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu 2017) selgub, et 77% Eesti üle 15- aastastest kasutajatest loeb alati läbi, milliste õigustega antud veebilehe või aplikatsiooni kasutamisel nõustuma peab, mis on iseenesest väga muljetavaldav number. Kuigi uuringust ei selgu kui suur osakaal vastanutest tegelikult ei saa nendest õigustest aru, siis tõmmatakse paralleel rahuvsvaheliselt läbiviidud uuringule. Iga sotsiaalmeedia platvormi kasutama asumisega nõustub kasutaja teatud õigustega, nii näiteks on õigus Facebook’il jagada, aga mitte müüa, kasutajate Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu 2017) selgub, et 77% Eesti üle 15- aastastest kasutajatest loeb alati läbi, milliste õigustega antud veebilehe või aplikatsiooni kasutamisel nõustuma peab, mis on iseenesest väga muljetavaldav number. Kuigi uuringust ei selgu kui suur osakaal vastanutest tegelikult ei saa nendest õigustest aru, siis tõmmatakse paralleel rahuvsvaheliselt läbiviidud uuringule. Iga sotsiaalmeedia platvormi kasutama asumisega nõustub kasutaja teatud õigustega, nii näiteks on õigus Facebook’il jagada, aga mitte müüa, kasutajate Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu 2017) selgub, et 77% Eesti üle 15- aastastest kasutajatest loeb alati läbi, milliste õigustega antud veebilehe või aplikatsiooni kasutamisel nõustuma peab, mis on iseenesest väga muljetavaldav number. Kuigi uuringust ei selgu kui suur osakaal vastanutest tegelikult ei saa nendest õigustest aru, siis tõmmatakse paralleel rahuvsvaheliselt läbiviidud uuringule. Iga sotsiaalmeedia platvormi kasutama asumisega nõustub kasutaja teatud õigustega, nii näiteks on õigus Facebook’il jagada, aga mitte müüa, kasutajate Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu Pepu pepu Pepu pepu Pepu'
words = sentence.split()
print(len(words))

ner_results = nlp(sentence)
print(ner_results)

